### PR TITLE
escape: add exit-on-escape

### PR DESCRIPTION
**Pull request by JakubVanek**
Hi everyone,

this PR adds a new module for escape key detection. Now, by default, if escape key is pressed, then the program is exited via `exit(0)`. However this behavior is configurable via both a new API and an old NXC-style API.

I have built it with a background thread that monitors the state of the EXIT/escape button. The thread is started on-demand when monitoring is enabled (however this is the default). If the user does not want to have this thread running, a call to `TerminatorDisable()` or `SetLongAbort(TRUE)` will stop it.

I have tried to use pthread mutexes & condition variables to eliminate all data races that might occur. However I know of an edge case that when TerminatorEnable and TerminatorDisable are called concurrently, there might be a deadlock. This is because the condition variable wait will unlock the mutex in question and allow the `esc_do_spin` flag to be overriden.

I have tested the code with the following program.
```c
#include <ev3.h>

int main() {
    PlayTone(800, 100);
    Wait(2000);

    TerminatorDisable();
    PlayTone(500, 100);
    Wait(2000);

    TerminatorEnable(0);
    PlayTone(800, 100);
    Wait(2000);

    TerminatorDisable();
    PlayTone(500, 100);
    Wait(2000);
    return 0;
}
``` 

Best regards,

Jakub

### CODE REVIEW

**Comment by JakubVanek** [comment]
I think that this is partially a short-term solution (which is both good and bad).
* Pros:
   * it does not introduce breaking changes to the source code.
   * It is more or less self-contained.
* Cons:
   * If we add a global management thread one day, this thread will have an unnecessary cost. If we don't want to have an overhead of an extra thread, the monitoring functionality will have to be reimplemented there.

I think that a background thread would enable monitoring of long/short button presses & maybe asynchronous sensor configuration. However this would require more extensive changes.

**Comment by simonedegiacomi** [comment]
Hi @JakubVanek,
I just wanted for you to know that, to avoid the thread management, you could try to use the timer capabilities provided by [ev3_timer](https://github.com/c4ev3/EV3-API/blob/master/API/ev3_timer.c) :-)

If I'm not wrong, they are already used to update the screen (see [here](https://github.com/c4ev3/EV3-API/blob/master/API/ev3_lcd.c#L386)).

**Comment by JakubVanek** [comment]
Oh, that's nice :smile:  I haven't looked into timers previously, but indeed it could make the code a lot simpler. I'll try to rework it.

**Comment by JakubVanek** [comment]
Hmmm, it seems that it is not that easy.

The handler of ev3_timer runs in the context of a signal handler. However, in the handler I also need to lock the data mutex, otherwise a different thread could just be setting the variable and this would trigger a data race and Undefined Behaviour(TM). However, the handler can be run in the thread that has just locked the lock, so I would get a deadlock.

I see some ways how to fix this:
* disable signal handler while accessing the shared state,
* set the mutex to recursive mode,
* use some atomic primitive to avoid the need for a mutex (I found somewhere that a semaphore could help)
* use atomic variables instead of locks.

**Comment by JakubVanek** [comment]
I will try to rework this PR to extend the ev3_button code in such a way that enables long presses (and press-escape-to-exit) to work.

**Comment by a3f** [comment]
Ok, feel free to send a pull request when you're ready.

**Pull request closed without merging**
