### PR TITLE
Fixed some language problems in commads.pdf.

### PR DESCRIPTION
**Pull request by Davester47**
I changed some bad English in the docs, and changed 'und' to 'and' in one of the titles. I used Libreoffice Draw to edit it, so it may have caused some compatibility issues, but hopefully not. The commands.pdf also shrank down to a quarter of its former size: 400kb to 100kb.

### CODE REVIEW

**Comment by Davester47** [comment]
I also added changed the Makefile to use ranlib on libev3api.a

**Comment by a3f** [comment]
> I also added changed the Makefile to use ranlib on libev3api.a

Manpage says "The GNU ranlib program is another form of GNU ar; running ranlib is completely equivalent to executing ar -s". We already use `ar rcs`, so I am not sure what good adding ranlib here does?

**Comment by Davester47** [comment]
I reverted it.

**Comment by a3f** [comment]
Merged, thanks. If you would like to submit documentation in another format, feel free. :D

**Pull request merged**
